### ISSUE TITLE
No Screenshots on README

### ISSUE THREAD

**Issue by abitrolly** [Camji55/git2svg#1]
README is missing screenshots demoing usage and result.

**Comment by Camji55** [comment]
@abitrolly Can you be a little more descriptive as to what the issue is? What does the terminal output? Is the file created?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Camji55** [comment]
@abitrolly Or are you referring to the README?

**Comment by Camji55** [comment]
Usage gif & result image displayed.

Thank you!

**Comment by abitrolly** [comment]
Nice. The `gif` is big for that kind of info shown, but I can not immediately say the ways to crop it.

It might worth to mention that the tool scrapes SVG from contribution page and doesn't draw it from ground up itself.

**Comment by Camji55** [comment]
That is a good idea! Thank you.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Camji55** [comment]
Gif font size increased and disclosure added. Thanks for the suggestions @abitrolly.
